-- ============================================================================
-- Flyway V10 — executable copy of database/schema/09_overdue_alerts.sql.
-- Do not edit after it has been applied anywhere; add a new V11_... instead.
-- ============================================================================

CREATE TABLE alerts (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  type             VARCHAR2(30) NOT NULL,
  booking_id       NUMBER NOT NULL,
  equipment_id     NUMBER NOT NULL,
  status           VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
  message          VARCHAR2(500) NOT NULL,
  resolution_note  VARCHAR2(500),
  resolved_by      NUMBER,
  resolved_at      TIMESTAMP WITH TIME ZONE,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_alerts_type CHECK (type IN ('OVERDUE')),
  CONSTRAINT ck_alerts_status CHECK (status IN ('OPEN', 'RESOLVED')),
  CONSTRAINT fk_alerts_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
  CONSTRAINT fk_alerts_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
  CONSTRAINT fk_alerts_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (id)
);

CREATE INDEX ix_alerts_status ON alerts (status);
CREATE INDEX ix_alerts_booking ON alerts (booking_id);

COMMENT ON TABLE alerts IS 'Operational alerts. OVERDUE alerts are raised once per booking by the scheduler; staff resolve them.';
COMMENT ON COLUMN alerts.resolved_by IS 'users.id of the staff/admin who resolved the alert.';
