-- ============================================================================
-- Flyway V2 — executable copy of database/schema/01_roles_users.sql.
-- Do not edit after it has been applied anywhere; add a new V3__... instead.
-- ============================================================================

CREATE TABLE roles (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(30) NOT NULL,
  description VARCHAR2(255),
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_roles_name UNIQUE (name),
  CONSTRAINT ck_roles_name CHECK (name IN ('STUDENT', 'LAB_STAFF', 'ADMIN'))
);

COMMENT ON TABLE roles IS 'Application roles. Rows are seeded, never created at runtime.';
COMMENT ON COLUMN roles.name IS 'One of STUDENT, LAB_STAFF, ADMIN (enforced by ck_roles_name).';

CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(50) NOT NULL,
  email         VARCHAR2(255) NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  full_name     VARCHAR2(100),
  is_enabled    NUMBER(1) DEFAULT 1 NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT ck_users_enabled CHECK (is_enabled IN (0, 1))
);

COMMENT ON TABLE users IS 'Application users. Credential = password_hash only.';
COMMENT ON COLUMN users.password_hash IS 'BCrypt (or stronger) hash. NEVER plaintext — enforced by code review, no DB clearance can bypass it.';
COMMENT ON COLUMN users.is_enabled IS '1 = active, 0 = disabled. Boolean-as-NUMBER(1) Oracle convention.';
