-- ============================================================================
-- Flyway V4 — executable copy of database/schema/03_equipment.sql.
-- Do not edit after it has been applied anywhere; add a new V5__... instead.
-- ============================================================================

CREATE TABLE equipment (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  equipment_code     VARCHAR2(50) NOT NULL,
  name               VARCHAR2(150) NOT NULL,
  category           VARCHAR2(80) NOT NULL,
  description        VARCHAR2(1000),
  manufacturer       VARCHAR2(100),
  model              VARCHAR2(100),
  laboratory         VARCHAR2(100),
  condition          VARCHAR2(30) DEFAULT 'GOOD' NOT NULL,
  current_status     VARCHAR2(30) DEFAULT 'AVAILABLE' NOT NULL,
  maintenance_status VARCHAR2(30) DEFAULT 'OPERATIONAL' NOT NULL,
  created_by         NUMBER,
  created_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_equipment_code UNIQUE (equipment_code),
  CONSTRAINT ck_equipment_condition CHECK (condition IN ('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED')),
  CONSTRAINT ck_equipment_status CHECK (current_status IN ('AVAILABLE', 'RESERVED', 'IN_USE', 'OVERDUE', 'MAINTENANCE', 'SENSOR_OFFLINE')),
  CONSTRAINT ck_equipment_maintenance CHECK (maintenance_status IN ('OPERATIONAL', 'DUE', 'IN_MAINTENANCE', 'OUT_OF_SERVICE')),
  CONSTRAINT fk_equipment_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX ix_equipment_status ON equipment (current_status);
CREATE INDEX ix_equipment_category ON equipment (category);

COMMENT ON TABLE equipment IS 'Laboratory equipment catalog. Identity data owned by catalog module; current_status owned by booking/QR/sensor modules.';
COMMENT ON COLUMN equipment.equipment_code IS 'Immutable business key (e.g. OSC-2026-001). Never updated.';
COMMENT ON COLUMN equipment.created_by IS 'users.id of the staff/admin who registered the item. Nullable for legacy imports.';
