-- ============================================================================
-- Flyway V8 — executable copy of database/schema/07_sensor.sql.
-- Do not edit after it has been applied anywhere; add a new V9__... instead.
-- ============================================================================

ALTER TABLE equipment ADD (sensor_key_hash VARCHAR2(64));

COMMENT ON COLUMN equipment.sensor_key_hash IS 'SHA-256 of the device API key. NULL = no key provisioned, ingest rejected.';

CREATE TABLE sensor_events (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  equipment_id  NUMBER NOT NULL,
  status        VARCHAR2(20) NOT NULL,
  current_value NUMBER(10, 3),
  occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at   TIMESTAMP WITH TIME ZONE NOT NULL,
  stale         NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT ck_sensor_stale CHECK (stale IN (0, 1)),
  CONSTRAINT ck_sensor_status CHECK (status IN ('IDLE', 'IN_USE', 'OFFLINE', 'FAULT')),
  CONSTRAINT fk_sensor_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id)
);

CREATE INDEX ix_sensor_equipment_time ON sensor_events (equipment_id, occurred_at);

COMMENT ON TABLE sensor_events IS 'Append-only raw device reports. Untrusted input: validated, range-checked and staleness-flagged at ingest.';
COMMENT ON COLUMN sensor_events.stale IS '1 = occurred_at is older than the staleness threshold (accepted but flagged).';
