-- ============================================================================
-- 04_bookings.sql — BOOKINGS table (Module: Booking).
-- Authored copy; the executable copy is backend/.../db/migration/V5__bookings.sql.
-- Overlap prevention: Oracle has no EXCLUDE constraints, so races are closed by
-- locking the EQUIPMENT row (SELECT ... FOR UPDATE) inside the booking
-- transaction and then checking for overlapping active bookings. The
-- ck_bookings_time CHECK is a last-resort guard, not the conflict mechanism.
-- Active (blocking) statuses: CONFIRMED, CHECKED_IN, OVERDUE.
-- CHECKED_IN / COMPLETED / OVERDUE transitions arrive with the QR / overdue
-- modules; this module owns PENDING → CONFIRMED / REJECTED / CANCELLED.
-- ============================================================================

CREATE TABLE bookings (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  equipment_id NUMBER NOT NULL,
  user_id     NUMBER NOT NULL,
  start_time  TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time    TIMESTAMP WITH TIME ZONE NOT NULL,
  status      VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  purpose     VARCHAR2(500) NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_bookings_time CHECK (end_time > start_time),
  CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'OVERDUE', 'REJECTED')),
  CONSTRAINT fk_bookings_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_bookings_equipment_time ON bookings (equipment_id, start_time, end_time);
CREATE INDEX ix_bookings_user ON bookings (user_id);

COMMENT ON TABLE bookings IS 'Equipment reservations. Overlap safety = equipment row lock + active-booking check in BookingService.';
COMMENT ON COLUMN bookings.status IS 'PENDING → CONFIRMED/REJECTED (staff); CONFIRMED → CANCELLED (owner/staff). CHECKED_IN/COMPLETED/OVERDUE owned by QR/overdue modules.';
