-- ============================================================================
-- 05_qr_usage_audit.sql — QR tokens, usage sessions, audit events (Module: QR).
-- Authored copy; executable copy is backend/.../db/migration/V6__qr_usage_audit.sql.
-- QR tokens are opaque random values: only their SHA-256 hash is stored, each
-- token is single-use, and every validation outcome is written to audit_events
-- (failures via an independent transaction so rollbacks cannot erase them).
-- ============================================================================

CREATE TABLE qr_tokens (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  booking_id  NUMBER NOT NULL,
  token_hash  VARCHAR2(64) NOT NULL,
  expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  used        NUMBER(1) DEFAULT 0 NOT NULL,
  used_at     TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_qr_token_hash UNIQUE (token_hash),
  CONSTRAINT ck_qr_used CHECK (used IN (0, 1)),
  CONSTRAINT fk_qr_booking FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

CREATE INDEX ix_qr_booking ON qr_tokens (booking_id);

COMMENT ON TABLE qr_tokens IS 'Single-use opaque check-in tokens. Only SHA-256 hashes are stored; raw values exist only in the generate response.';
COMMENT ON COLUMN qr_tokens.used IS '1 = consumed by a check-in (or invalidated by regeneration).';

CREATE TABLE usage_sessions (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  booking_id       NUMBER NOT NULL,
  equipment_id     NUMBER NOT NULL,
  user_id          NUMBER NOT NULL,
  started_at       TIMESTAMP WITH TIME ZONE NOT NULL,
  ended_at         TIMESTAMP WITH TIME ZONE,
  duration_seconds NUMBER,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_session_booking UNIQUE (booking_id),
  CONSTRAINT fk_session_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
  CONSTRAINT fk_session_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
  CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users (id)
);

COMMENT ON TABLE usage_sessions IS 'One row per checked-in booking. duration_seconds is set at checkout.';
COMMENT ON COLUMN usage_sessions.duration_seconds IS 'Whole seconds between started_at and ended_at.';

CREATE TABLE audit_events (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  event_type     VARCHAR2(40) NOT NULL,
  actor_username VARCHAR2(50),
  entity_type    VARCHAR2(40),
  entity_id      NUMBER,
  detail         VARCHAR2(1000),
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_audit_entity ON audit_events (entity_type, entity_id);
CREATE INDEX ix_audit_type ON audit_events (event_type);

COMMENT ON TABLE audit_events IS 'Append-only trail. QR module writes QR_GENERATED / CHECKED_IN / CHECKED_OUT / QR_VALIDATION_FAILED; later modules extend the vocabulary.';
