-- ============================================================================
-- 09_overdue_alerts.sql — overdue detection support (Module: Overdue).
-- Authored copy; executable copy is backend/.../db/migration/V10__overdue_alerts.sql.
-- Detection is idempotent by construction: a booking flips to OVERDUE once, and
-- at most one OPEN alert exists per booking (enforced in OverdueService and
-- checked here with a unique filtered pattern via application logic — Oracle
-- has no partial unique indexes, so the service double-checks).
-- ============================================================================

CREATE TABLE alerts (
  id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  type             VARCHAR2(30) NOT NULL,
  booking_id       NUMBER NOT NULL,
  equipment_id     NUMBER NOT NULL,
  status           VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
  message          VARCHAR2(500) NOT NULL,
  resolution_note  VARCHAR2(500),
  resolved_by      NUMBER,
  resolved_at      TIMESTAMP WITH TIME ZONE,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_alerts_type CHECK (type IN ('OVERDUE')),
  CONSTRAINT ck_alerts_status CHECK (status IN ('OPEN', 'RESOLVED')),
  CONSTRAINT fk_alerts_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
  CONSTRAINT fk_alerts_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
  CONSTRAINT fk_alerts_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (id)
);

CREATE INDEX ix_alerts_status ON alerts (status);
CREATE INDEX ix_alerts_booking ON alerts (booking_id);

COMMENT ON TABLE alerts IS 'Operational alerts. OVERDUE alerts are raised once per booking by the scheduler; staff resolve them.';
COMMENT ON COLUMN alerts.resolved_by IS 'users.id of the staff/admin who resolved the alert.';
